### ISSUE TITLE
[Mega-issue] Directional fan migration

### ISSUE THREAD

**Issue by PeccNeck** [new-frontiers-14/frontier-station-14#1980]
A mega-issue for tracking every ship and PoI currently in need of migration to directional fans.

## Points of Interest
- [X] Frontier Outpost
- [X] NFSD Outpost
- [X] Expeditionary Lodge
- [x] Trade Outpost (#2366)
- [X] Cargo Depot (+alt) (#2155)
- [X] Anomalous Geode (#2135)
- [X] Anomalous Lab (#2136)
- [X] Tinnia's Rest (#2144)
- [X] Omnichurch Beacon (#2140)
- [X] The Pit (#2153)
- [X] Courthouse (#2141)
- [x] Crazy Casey's Casino (#2367)
- [X] Derelict McCargo / McHobo (@Tych0theSynth)
- [x] Listening Point Bravo (@dvir001)
- [x] North Pole (#2368)

### Standard Shipyard
- [X] DC McCargo
- [x] HS Garden (#2052)
- [x] ICR Chisel (#2053)
- [x] KC Crescent (#1945)
- [x] KL Bulker (#2057)
- [x] LVHI Harbormaster (#1805)
- [x] LVHI Kilderkin (#1805)
- [x] LVHI Lantern (#1805)
- [x] LVHI Legman (#1805)
- [x] LVHI Liquidator (#1805)
- [x] LVHI Pioneer (#1805)
- [x] LVHI Searchlight (#1805)
- [x] NC Barge (#2066)
- [x] NC Bocadillo (#2058)
- [x] NC Hauler (#2067)
- [x] NC Kestrel (#2054)
- [x] NC Loader (#2051)
- [x] NC Personal Transport (#2202)
- [x] NC Piecrust (#1992)
- [x] NC Placebo (#2068)
- [x] NC Prospector (#2050)
- [x] NC Skipper (#2069)
- [x] NM Apothecary (#1926)
- [x] NM Caduceus (#2166)
- [x] NM Eagle (#2266)
- [x] NM Spirit (#2059)
- [x] NM Stasis (#1967)
- [x] NR Investigator (#2090)
- [x] NR Phoenix (#2091)
- [x] NR Sparrow (#2106)
- [x] NR Spectre (#2105)
- [x] NT Comet (#2055)
- [x] NT Construct (#2107)
- [x] NT Honker (#2108)
- [x] NT Stellaris (#1935)
- [x] NT Vagabond (#1976)
- [x] SBB Bookworm (#2043)
- [x] SBB Ceres (#2041)
- [x] SBB Hammer (#2323)
- [x] SBB Lyrae (#2016)
- [x] SBI Beaker (#2110)
- [X] ~~SBI Crown~~ Retired pending rework.
- [x] SLI Bazaar (#2056)
- [x] SSS Camper (#2115)
- [x] UW Akupara (#1979)
### Scrapyard
- [x] NSV Disciple (#2079)
- [x] NT Bison (#2080)
- [x] SV Nugget (#2081)
- [x] SV Orange (#2082)
- [x] SV Point (#2083)
- [x] UAC Canister (#2084)
### Frontier Outpost Staff
- [x] LVHI Broom (#1805)
- [x] NC Mail Pod (#1981)
- [x] NC Parcel (#1981)
- [x] NT Bottleneck (#1996)
- [X] SBI Watchdog
### NFSD
- [x] NSF Broadhead (#2033)
- [x] NSF Empress (#2104)
- [x] NSF Hospitaller (#2194)
- [x] ~~NSF Inquisitor (#2169)~~
- [x] NSF Interceptor (#2199)
- [x] NSF Marauder (#2160)
- [x] NSF Prowler (#2094)
- [x] NSF Templar (#2186)
- [x] NSF Wasp (#2277)
### Expeditions
- [x] DYS Dove (#2085)
- [x] DYS Dragonfly (#2086)
- [x] KC Anchor (#2087)
- [x] KC Pathfinder (#2060)
- [x] KC Sprinter (#2062)
- [x] LVHI Brigand (#1805)
- [x] ~~NT Dart-X (#2089)~~
- [x] NT Gasbender (#1805)
- [x] SLI Gourd (#2088)
- [x] UAC Ambition (#2372)
### Pirates/Syndicates
- [X] Barnacle (#2097)
- [x] Bocakillo (#2469)
- [x] Falcon (#2098)
- [x] Menace (#1981)
- [x] Schooner (#2099)
- [x] Hunter (#2295)
- [x] Infiltrator (#2468)
### Other
- [X] DC McDelivery
- [x] Fishbowl (#1995)
- [x] NSF Cleric (#2243)
- [x] NSF Fighter (#2243)
- [x] NSF Rogue (#2243)
- [X] Public Transport Shuttle
- [X] Syndicate Supply Pod

**Comment by arimah** [comment]
All SBB ships will be updated by myself and @Tych0theSynth. I will edit the issue to reflect this.

**Comment by Tych0theSynth** [comment]
Prowler #2094 
Broadhead #2033 
From what I can see in game, the Derelict McCargo has directional fans already.

**Comment by AF-Buyrcsp2** [comment]
Camper https://github.com/new-frontiers-14/frontier-station-14/pull/2115

**Comment by chrome-cirrus** [comment]
Anomalous Geode [2135](https://github.com/new-frontiers-14/frontier-station-14/pull/2135)

**Comment by chrome-cirrus** [comment]
Anomalous Lab [2136](https://github.com/new-frontiers-14/frontier-station-14/pull/2136)

**Comment by chrome-cirrus** [comment]
Omnichurch Beacon [2140](https://github.com/new-frontiers-14/frontier-station-14/pull/2140)

**Comment by chrome-cirrus** [comment]
Courthouse [2141](https://github.com/new-frontiers-14/frontier-station-14/pull/2141)

**Comment by chrome-cirrus** [comment]
Tinnia's Rest [2144](https://github.com/new-frontiers-14/frontier-station-14/pull/2144)

**Comment by chrome-cirrus** [comment]
Cargo depot (and alt) [2155](https://github.com/new-frontiers-14/frontier-station-14/pull/2155)

**Comment by chrome-cirrus** [comment]
NFSD Marauder [2160](https://github.com/new-frontiers-14/frontier-station-14/pull/2160)

**Comment by chrome-cirrus** [comment]
NSF Inquisitor [2169](https://github.com/new-frontiers-14/frontier-station-14/pull/2169)

**Comment by chrome-cirrus** [comment]
NSF Templar [2186](https://github.com/new-frontiers-14/frontier-station-14/pull/2186)

**Comment by chrome-cirrus** [comment]
NSF Interceptor [2199](https://github.com/new-frontiers-14/frontier-station-14/pull/2199)

**Comment by blackknight954** [comment]
UAC Ambitino https://github.com/new-frontiers-14/frontier-station-14/pull/2309

**Comment by PeccNeck** [comment]
Bocakillo got merged, that's the last of them; all done!

**Comment by arimah** [comment]
> Someone should find the maintainer of the Bocakillo and ask them what the holdup was.

Are comments like that really necessary?
