### ISSUE TITLE
New Frontier Sheriffs Department Tasklist

### ISSUE THREAD

**Issue by Kesiath** [new-frontiers-14/frontier-station-14#224]
## Overview
Introduce the New Frontier Sheriffs Department, a respriting and renaming effort to bring the security department to the, more thematically appropriate, sheriffs department.

**Tasks**
- [x] Create a new headset, titled NFSD, that won't be mapped inside of expeditions, and is exclusive to NFSD officers.
- [x] Create new uniforms and accessories modeled after Sheriffs Department attire, namely a new uniform for Sheriff, Bailiff, and Deputies, as well as their appropriate headgear. (Campaign Hat?!)
- [x] Alter items, such as PDAs, or create copies of said items, which reflect the name changes.
- [x] Rename Head of Security to Sheriff, rename Warden to Bailiff, and rename Security Officers to Deputies.
- [x] Fix gear given to roles on round-start to be NFSD gear.

There might be some other concepts I'm missing here, but I think that's the most important flavor-wise to get this rolling.

**Comment by Cheackraze** [comment]
As far as security re-branding goes, the black and red actually looks decent and so I would consider uniform resprites as long-term, or at the very least non-essential to implementing the other changes

**Comment by Kesiath** [comment]
https://github.com/new-frontiers-14/frontier-station-14/pull/246 handles a good chunk of this.
