### ISSUE TITLE
[Mega-issue] The big list of ship reworks

### ISSUE THREAD

**Issue by TsjipTsjip** [new-frontiers-14/frontier-station-14#908]
Draft of the new mapping guidelines were released on discord a while back, and many ships currently on the roster do not fit the bill anymore. This is a mega-issue listing all ships currently in the game, and if there needs to be work done on them. Please actively comment on this issue with PR links if you believe a checkbox should be ticked.

A checkbox can be ticked if and only if a ship rework is completed and merged.
A PR can be linked as soon as it is open to signify that this ship is actively being worked on.
Please mention this issue in ship rework PR's, as this automates a lot of this.

A ship being on this list merely means it exists at the time of writing the issue. It does no automatically mean there is something wrong with it, just that this needs to be checked.

**Standard shipyard:**
- [x] DC MCCargo ( #907 and #940 )
- [x] HS Garden ( #913 )
- [x] ICR Chisel ( #912 )
- [x] KC Crescent ( #915 )
- [x] KL Bulker ( #914 )
- [x] NC Barge ( #919 )
- [x] NC Bocadillo ( #918 )
- [x] NC Kilderkin ( #791 )
- [x] NC Lantern ( #898 )
- [x] NC Legman ( #892 )
- [x] NC Loader ( #1010 )
- [x] NC Mail Truck ( #920 )
- [x] NC Mission ( #925 )
- [x] NC Personal Transport ( #924 )
- [x] NC Pioneer ( #900 )
- [x] NC Prospector ( #934 )
- [x] NC Skipper ( #949 )
- [ ] NM Caduceus (Reported issues with wallmount nanovends and accessibility of them.)
- [x] NM Helix ( #953 )
- [x] NM Pulse ( #956 )
- [x] NM Searchlight ( #897 )
- [x] NR Sparrow ( #955 )
- [x] NR Condor
- [x] NR Investigator ( #1030 )
- [x] NR Phoenix ( #1007 )
- [x] NSS Spectre
- [x] NT Comet ( #1008 )
- [x] NT Construct
- [x] NT Esquire ( #951 )
- [x] NT Honker ( #1006 )
- [x] NT Kestrel ( #946 )
- [x] NT Liquidator (To be renamed NC Liquidator) ( #895 )
- [x] NT Rigger (To be renamed NT Gasbender) ( #896 )
- [x] NT Rosebud MKI ( #948 )
- [x] NT Stellaris (#1963)
- [x] NT WaveShot ( #944 )
- [x] SLI Bazaar ( #871 )
- [x] TC Metastable (Update mapchecker whitelist)

**Scrapyard:**
- [x] NT Bison (#2080)
- [x] SV Nugget ( #954 )
- [x] SV Orange
- [x] SV Tide
- [x] USS Mayflower ( #1002 )

**Expedition shipyard:**
- [x] DYS Dove ( #1027 )
- [x] DYS Dragonfly ( #1027 )
- [x] KC Anchor (Update mapchecker whitelist)
- [x] KC Pathfinder (Update mapchecker whitelist) ( #926 )
- [x] KC Sprinter
- [x] NT Courser-X (Update mapchecker whitelist)
- [x] NT Dart-X (Update mapchecker whitelist)
- [x] NT Praeda (Update mapchecker whitelist) ( #950 )
- [x] NT Rosebud MKII (Update mapchecker whitelist)
- [x] SLI Gourd ( #871 ) (Potentially rework pipes still? / Reconsider price point)

**NFSD shipyard:** (NSF stands for Nanotrasen Security Force and is correct. It is not a typo.)
- [x] NSF Empress (Consider removing syndicate shuttle console) ( #909 )
- [x] NSF Hospitaller ( #910 )
- [x] NSF Inquisitor ( #911)
- [x] NSF Interceptor
- [x] NSF Marauder (Uses a syndicate shuttle console)
- [x] NSF Opportunity ( #994 )
- [x] NSF Prowler (#1254)
- [x] NSF Templar
- [x] NSF Wasp

**Black market shipyard:**
- [x] Hunter
- [x] Infiltrator
- [x] Schooner (Update mapchecker whitelist)

**Other:**
- [x] DC McDelivery ( #907 and #940 )
- [x] NSF Cleric
- [x] NSF Fighter
- [x] NSF Rogue

**Comment by arimah** [comment]
Missing: NC Skipper

**Comment by TsjipTsjip** [comment]
Needs reopening, issue was closed erroneously.

**Comment by Cheackraze** [comment]
dove and dragonfly recently got updated but the map file checker needs to be changed still i believe

**Comment by Tych0theSynth** [comment]
I've addressed both the Prowler (#1254) and Interceptor (#1245) as part of issue #1230.

**Comment by BlueHNT** [comment]
add Beaker to the list please. That thing needs an update.

**Comment by dvir001** [comment]
> add Beaker to the list please. That thing needs an update.

Care to say why?

**Comment by Tych0theSynth** [comment]
Honestly with how long this issue has been open and the number of reworks done since, we should probably have a new issue

**Comment by dvir001** [comment]
Going to close this as Caduceus has a replacement open and the rest are done.
